blank_issues_enabled: false
contact_links:
  - name: Suggestion
    url: https://discord.gg/SxVJ2fyekc
    about: Give your feedback or suggestion on the Discord community.
contact_links:
  - name: Help
    url: https://discord.gg/fUez4JNNGf
    about: If you need help then come and ask on the Discord community.