name: Dev Update

on:
  push:
    branches:
      - dev

jobs:
  updateVersion:
    permissions:
      contents: write

    if: ${{ github.repository == 'FredyJabe/aeyama' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Version Update
      run: |
        python .github/workflows/scripts/version.py
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m 'Automatic Version Update'
        git push