name: Main Build

on:
  workflow_dispatch:

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17.0.7
        distribution: oracle
        cache: gradle
    - name: Build mod JAR
      run: chmod +x ./gradlew; ./gradlew deploy
    - name: Get current version
      run: |
        version=$(${{github.workspace}}/gradlew -q printVersion)
        echo "version=$version" >> $GITHUB_ENV
    - name: Upload built JAR file
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}-${{ env.version }}
        path: build/libs/${{ github.event.repository.name }}-${{ env.version }}.jar